name: Site CI

on:
  push:
    branches:
    - master

env:
  GIT_USER: luswdev
  GIT_EMAIL: 610721230@gms.ndhu.edu.tw
  DEPLOY_REPO: blog
  DEPLOY_BRANCH: gh-pages

jobs:
  build:
    name: Build on node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Setup timezone
        run: |
          export TZ="Asia/Taipei"
          export NOW=$(date +"%Y-%m-%d %H:%M:%S")
          sudo timedatectl set-timezone "Asia/Taipei"

      - name: Configuration environment
        env:
          HEXO_DEPLOY_PRI: ${{ secrets.HEXO_DEPLOY_PRI }}
        run: |          
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name $GIT_USER
          git config --global user.email $GIT_EMAIL
        
      - name: Save commit history
        uses: actions/checkout@v2
        with:
          repository: ${{ env.GIT_USER }}/${{ env.DEPLOY_REPO }}
          ref: ${{ env.DEPLOY_BRANCH }}
          path: .deploy_git

      - name: Install dependencies
        run: |
          npm i -g hexo-cli
          npm i

      - name: Deploy hexo
        run: |
          hexo generate
          hexo deploy